"""Download published stage images for a release; requires Pillow. Never runs in-app."""
import argparse
import hashlib
import io
import json
import sqlite3
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import urlsplit
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh', action='store_true', help='Redownload even when URL and hash match')
    args = parser.parse_args()
    manifest_path = ROOT / 'assets/stage_images.json'
    previous = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    with sqlite3.connect((ROOT / 'assets/database/camino.sqlite').as_uri() + '?mode=ro', uri=True) as db:
        rows = db.execute('SELECT ID, stageMap1920URL, stageElevationChartURL FROM stages ORDER BY ID').fetchall()
    jobs = [(stage, kind, url) for stage, map_url, chart_url in rows for kind, url in [('stage_maps', map_url), ('elevation_charts', chart_url)] if url]
    missing = [{'stage': stage, 'kind': kind} for stage, map_url, chart_url in rows for kind, url in [('stage_maps', map_url), ('elevation_charts', chart_url)] if not url]
    def fetch(job):
        stage, kind, url = job
        parsed = urlsplit(url)
        if parsed.scheme != 'https' or parsed.hostname != 'res.cloudinary.com':
            raise ValueError(f'Stage {stage}: expected a Cloudinary HTTPS image URL')
        key = f'{kind}/{stage}'
        old = previous.get('images', {}).get(key, {})
        old_path = ROOT / old.get('asset', '__missing__')
        if not args.refresh and old.get('url') == url and old_path.is_file() and hashlib.sha256(old_path.read_bytes()).hexdigest() == old.get('sha256'):
            return key, old
        request = urllib.request.Request(url, headers={'User-Agent': 'CaminoGuideOfflineMVP-AssetBuilder/1.0'})
        with urllib.request.urlopen(request, timeout=60) as response:
            data = response.read()
        with Image.open(io.BytesIO(data)) as image:
            width, height = image.size
            extension = {'JPEG': 'jpg', 'PNG': 'png', 'WEBP': 'webp'}.get(image.format)
            image.verify()
        if not extension:
            raise ValueError(f'Unsupported image format for stage {stage}')
        asset = f'assets/{kind}/stage_{stage}.{extension}'
        path = ROOT / asset
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(path.suffix + '.tmp')
        temporary.write_bytes(data)
        temporary.replace(path)
        print(f'Stage {stage}: {kind} {width}x{height}', flush=True)
        return key, {'asset': asset, 'url': url, 'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data), 'width': width, 'height': height}
    def attempt(job):
        try:
            return fetch(job)
        except Exception as error:
            stage, kind, url = job
            print(f'Unavailable: stage {stage} {kind}: {error}', flush=True)
            return f'{kind}/{stage}', {'url': url, 'error': str(error)}
    with ThreadPoolExecutor(max_workers=3) as pool:
        results = dict(pool.map(attempt, jobs))
    images = {key: value for key, value in results.items() if 'asset' in value}
    failures = {key: value for key, value in results.items() if 'error' in value}
    manifest = {'images': images, 'missing_source_urls': missing, 'unavailable': failures}
    temp = manifest_path.with_suffix('.tmp')
    temp.write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    temp.replace(manifest_path)
    # Generated lookup avoids network requests and supports original image formats.
    entries = '\n'.join(f"    '{key}': '{entry['asset']}'," for key, entry in images.items())
    (ROOT / 'lib/data/stage_image_assets.dart').write_text(
        "// Generated by tool/bundle_stage_images.py. Do not edit manually.\n"
        "class StageImageAssets {\n  static const paths = <String, String>{\n" + entries +
        "\n  };\n  static String? map(int stageId) => paths['stage_maps/$stageId'];\n"
        "  static String? elevation(int stageId) => paths['elevation_charts/$stageId'];\n}\n", encoding='utf-8')
    print(f"Bundled {len(images)} images, {sum(i['bytes'] for i in images.values()) / 1024 / 1024:.1f} MiB; {len(missing)} missing source URLs.")

if __name__ == '__main__':
    main()
